'''
Filtered stream
needs tweepy installed
'''

import tweepy

CONSUMER_KEY = 'Z8WSUWYeqM50xqvFM6RA'
CONSUMER_SECRET = 'bgK6lGYPCc3tZHxJtSXGeNftyxje0uwzu3gfonzU'
ACCESS_TOKEN = '261549959-PTQfNHLF4e12q7Vy5TGydLMwYZhxZbTeziRMZlZE'
ACCESS_TOKEN_SECRET = 'juRejtsBaitG8xCDc1wnJLi1r8tsz0rMJjN4PvdM'

auth = tweepy.auth.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

#Tweepy StreamListener class from http://andrewbrobinson.com/2011/07/15/using-tweepy-to-access-the-twitter-stream/
class StreamListener(tweepy.StreamListener):
    def __init__(self, api=None):
            self.file = open('Q1B.txt', 'w')
            super(StreamListener, self).__init__(api)
    def on_status(self, status):
        try:
            #clean up twitter status (remove newlines)
            self.file.write('%s\t%s\n' % (status.created_at, (status.text).replace('\n', '').replace('\r', '')))
        except:
            # Catch any unicode errors while printing to console
            # and just ignore them to avoid breaking application.
            pass
    def on_error(self, status_code):
        print 'An error has occured! Status code = %s' % status_code
        return True  # keep stream alive
    def on_timeout(self):
        print 'Snoozing Zzzzzz'

listener = StreamListener()
stream=tweepy.Stream(auth=auth, listener=listener, timeout=3000)
# terms to filter the stream by
# setTerms = ['football','fumble','nfl','interception']
setTerms = ["American Football Conference",
"Punts blocked",
"Field goals blocked",
"Completion",
"Carries",
"Defensive Lineman",
"Fumble",
"Forced fumbles",
"Field goal",
"Field goals",
"Fumble",
"Interceptions",
"Kicker",
"Kick Return",
"Lost fumbles",
"Moneyline",
"National Football Conference",
"Offensive Lineman",
"Passes deflected",
"Punt Return",
"Rushes",
"Rushing attempts",
"Running Back",
"Time of possession",
"Quarterback",
"Quarter",
"Safety",
"Sacks",
"Solo tackles",
"Straight Up",
"Tackles",
"Touchback",
"Touchdown",
"Targets",
"Total plays",
"Total",
"Extra points",
"Extra point",
"Yards per attempt",
"Yards",
"Arizona Cardinals",
"Atlanta Falcons",
"Baltimore Ravens",
"Buffalo Bills",
"Carolina Panthers",
"Chicago Bears",
"Cincinnati Bengals",
"Cleveland Browns",
"Dallas Cowboys",
"Denver Broncos",
"Detroit Lions",
"Green Bay Packers",
"Houston Texans",
"Indianapolis Colts",
"Jacksonville Jaguars",
"Kansas City Chiefs",
"Miami Dolphins",
"Minnesota Vikings",
"New England Patriots",
"New Orleans Saints",
"New York Giants",
"New York Jets",
"Oakland Raiders",
"Philadelphia Eagles",
"Pittsburgh Steelers",
"San Diego Chargers",
"Seattle Seahawks",
"San Francisco ","49ers",
"Saint Louis Rams",
"Tampa Bay Buccaneers",
"Tennessee Titans",
"Washington Redskins",
"Assistant Coach",
"Artificial Turf",
"Astroturf",
"Audible",
"Back Judge",
"Backfield",
"Balanced Line",
"Ball Carrier",
"Bird Cage",
"Blackout",
"Blind Side",
"Blitz",
"Block",
"Bootleg",
"Bowl Game",
"Bump and Run",
"Buttonhook",
"Canadian Football",
"CFL",
"Cheat Sheet",
"Check Off",
"Chop Block",
"Clipping",
"Clothesline",
"Coffin Corner",
"Coin Toss",
"Completion",
"Conferences",
"Controlling the Clock",
"Cornerback",
"Coverage",
"Crackback Block",
"Cut Back",
"Dead Ball",
"Defense",
"Defensive Back",
"Defensive Backfield",
"Defensive End",
"Defensive Holding",
"Defensive Line",
"Defensive Lineman",
"Defensive Tackle",
"Defensive Team",
"Delay of Game",
"Dime Back",
"Dime Coverage",
"Dime Package",
"Division",
"Double Coverage",
"Double Foul",
"Double Team",
"Down and In",
"Down and Out",
"Down Box",
"Down Lineman",
"Draft Choice",
"Drop Back",
"Drop Kick",
"Eligible Receiver",
"Encroachment",
"End Line",
"End Zone",
"Excessive Time Outs",
"Extra Point",
"Face Mask",
"Fair Catch",
"Fair Catch Interference",
"Faking a Roughing",
"False Start",
"Fantasy Football",
"Fantasy League",
"Field Goal",
"Field Judge",
"Field of Play",
"Field Position",
"First and Ten",
"First Down",
"Flag Football",
"Flanker",
"Forward Pass",
"Forward Progress",
"Franchise Player",
"Free Agency",
"Free Agent",
"Free Kick",
"Free Safety",
"Front Four",
"Front Seven",
"Fullback",
"Fumble",
"Game Ball",
"Goal Line",
"Goal Line Stand",
"Goalpost",
"Gridiron",
"Hail Mary",
"Halfback",
"Handoff",
"Hands Team",
"Hang Time",
"Hash Marks",
"Head Coach",
"Head Linesman",
"Helping the Runner",
"Heisman Trophy",
"Hitch and Go",
"Hole Number",
"Home Field Advantage",
"Hook and Ladder",
"Hot Receiver",
"Hurry up Offense",
"I Formation",
"Illegal Formation",
"Illegal Motion",
"Illegal Procedure",
"Illegal Shift",
"In Bounds",
"Incomplete Pass",
"Incompletion",
"Ineligible Receiver Downfield",
"Intentional Grounding",
"Interception",
"Interference",
"Kicking an Opponent",
"Kicking Game",
"Kickoff",
"Kick Returner",
"Linebacker",
"Line Judge",
"Lineman",
"Linemen",
"Line of Scrimmage",
"Line to Gain",
"Live Ball",
"Long Snapper",
"Loose Ball",
"Man in Motion",
"Man to Man Coverage",
"Middle Guard",
"Midfield",
"Mousetrap",
"Multiple Offense",
"National Football League",
"Necessary Line",
"Neutral Zone",
"NFL",
"NFL Championship",
"Nickel Back",
"Nickel Defense",
"Nose Guard",
"Nose Tackle",
"Oddsmaker",
"Offending Team",
"Offensive Backfield",
"Offensive Holding",
"Offensive Line",
"Offensive Linemen",
"Offensive Pass Interference",
"Off-Season",
"Offside",
"Off-Tackle",
"Onside Kick",
"Open Up Holes",
"Open Receiver",
"Out of Bounds",
"Out of Bounds at Snap",
"Outside",
"Overtime",
"Pass Defender",
"Pass Interference",
"Pass Pattern",
"Pass Protection",
"Pass Route",
"Pass Rush",
"Passing Game",
"PAT",
"Penalty",
"Personal Foul",
"Pick Off",
"Pigskin",
"Piling On",
"Pistol Formation",
"Pitch Out",
"Placekick",
"Placekicker",
"Play-Action Pass",
"Playbook",
"Play Clock",
"Playmaker",
"Playoffs",
"Pocket",
"Point After Touchdown",
"Point Spread",
"Pooch Kick",
"Possession",
"Post-Season",
"Power Sweep",
"Preseason",
"Previous Spot",
"Primary Receiver",
"Pump Fake",
"Punt",
"Punter",
"Punt Return",
"Pylon",
"Quarterback",
"Quarterback Rating",
"Quarterback Sneak",
"Quick Count",
"Quick Kick",
"Reading the Defense",
"Ready List",
"Receiver",
"Recover",
"Red Dog",
"Redshirt",
"Red Zone",
"Referee",
"Regular Season",
"Return",
"Returner",
"Reverse",
"Roll",
"Roll Out",
"Rookie",
"Roster",
"Roughing the Kicker",
"Roughing the Passer",
"Route",
"Runback",
"Running Back",
"Running Into the Kicker",
"Rush",
"Sack",
"Safety",
"Safety Blitz",
"Safety Valve",
"Salary Cap",
"Scheme",
"Scramble",
"Scrambler",
"Scrambling",
"Screen Pass",
"Scrimmage",
"Secondary",
"Second Forward Pass",
"Series",
"Shift",
"Shotgun",
"Side Judge",
"Sidelines",
"Signal Caller",
"Signals",
"Single Elimination",
"Single-Wing Formation",
"Slant",
"Slot",
"Snap",
"Spearing",
"Special Teams",
"Spike",
"Spiral",
"Split End",
"Spot",
"Square In",
"Square Out",
"Squib Kick",
"Stance",
"Stiff Arm",
"Straight Arm",
"Strength of Schedule",
"Striking an Official",
"Striking an Opponent",
"Strong Safety",
"Strong Side",
"Stunt",
"Substitution",
"Subway Alumni",
"Succeeding Spot",
"Suicide Squad",
"Super Bowl",
"Sweep",
"T-Formation",
"Tackle",
"Tailback",
"Takeaway",
"TD",
"Territory",
"Third-and-Long",
"Three-Point Stance",
"Tight End",
"Time Out",
"Too Many Men on the Field",
"Touchback",
"Touchdown",
"Trap Block",
"Trenches",
"Tripping",
"Turn In",
"Turn Out",
"Turnover",
"Two-Minute Warning",
"Two-Point Conversion",
"Umpire",
"Unbalanced Line",
"Unnecessary Roughness",
"Unsportsmanlike Conduct",
"Uprights",
"Veer",
"Vince Lombardi Trophy",
"Weak Side",
"Wideout",
"Wide Receiver",
"Wild Card",
"Wing Back",
"Winning Percentage",
"Wishbone Formation"]
stream.filter(None,setTerms)
